### ISSUE TITLE
Error running ncam embedded in gmoccapy/axis

### ISSUE THREAD

**Issue by gorbypark** [FernV/NativeCAM#1]
I am trying to run NativeCam embedded into axis/gmoccapy.  I get this error when running linuxcnc configs/sim/gmoccapy/ncam_demo/mill-mm.ini or any of the demo configs (both axis/gmoccapy).  Same error when I try adding the ncam config lines into an existing ini file.  Running ./ncam.py works fine.  I have run the setup.py script as well with no errors.  I believe it's the missing /usr/lib/pymodules/python2.7/gladevcp/catalogs but I'm not sure where to find it to sym link it in.

Thanks,
Gorbypark.

> NativeCAM info:
>     inifile = /home/mike/NativeCAM/configs/sim/gmoccapy/ncam_demo/mill-mm.ini
>     SYS_DIR = /usr/lib/pymodules/python2.7/gladevcp
>    NCAM_DIR = /home/mike/NativeCAM/configs/sim/gmoccapy/ncam_demo/ncam
>     program = /usr/lib/pymodules/python2.7/gladevcp/ncam.pyc
>   real path = /usr/lib/pymodules/python2.7/gladevcp/ncam.pyc
> 
> Traceback (most recent call last):
>   File "/usr/lib/pymodules/python2.7/gladevcp/ncam.py", line 2116, in **init**
>     self.update_user_tree(fromdirs, NCAM_DIR)
>   File "/usr/lib/pymodules/python2.7/gladevcp/ncam.py", line 2232, in update_user_tree
>     verbose = False
>   File "/usr/lib/pymodules/python2.7/gladevcp/ncam.py", line 278, in copy_dir_recursive
>     for p in os.listdir(fromdir) :
> OSError: [Errno 2] No such file or directory: '/usr/lib/pymodules/python2.7/gladevcp/catalogs'
> Xlib.protocol.request.QueryExtension

**Comment by FernV** [comment]
Find answer At
https://forum.linuxcnc.org/40-subroutines-and-ngcgui/31659-nativecam-is-features-renamed?start=80#81710

Le 17 oct. 2016 00:35, "Mike Hamilton" <notifications@github.com> a écrit :
>
> I am trying to run NativeCam embedded into axis/gmoccapy. I get this
error when running linuxcnc configs/sim/axis/mill.ini or any of the demo
configs. Same error when I try adding the ncam config lines into an
existing ini file. Running ./ncam.py works fine. I have run the setup.py
script as well with no errors.
>>
>> NativeCAM info:
>> inifile = /home/mike/NativeCAM/configs/sim/gmoccapy/ncam_demo/mill-mm.ini
>> SYS_DIR = /usr/lib/pymodules/python2.7/gladevcp
>> NCAM_DIR = /home/mike/NativeCAM/configs/sim/gmoccapy/ncam_demo/ncam
>> program = /usr/lib/pymodules/python2.7/gladevcp/ncam.pyc
>> real path = /usr/lib/pymodules/python2.7/gladevcp/ncam.pyc
>>
>> Traceback (most recent call last):
>> File "/usr/lib/pymodules/python2.7/gladevcp/ncam.py", line 2116, in init
>> self.update_user_tree(fromdirs, NCAM_DIR)
>> File "/usr/lib/pymodules/python2.7/gladevcp/ncam.py", line 2232, in
update_user_tree
>> verbose = False
>> File "/usr/lib/pymodules/python2.7/gladevcp/ncam.py", line 278, in
copy_dir_recursive
>> for p in os.listdir(fromdir) :
>> OSError: [Errno 2] No such file or directory:
'/usr/lib/pymodules/python2.7/glad

**Comment by FernV** [comment]
HI 

gladevcp is not right for SYS_DIR  It should be the directory where ncam.py is

program should be a link to ncam.py and real path should be ~/NativeCAM/ncam.py

It seems something needs to be changed in setup.py
I will not have access to my computer before next month but promise  to follow-up when I am back
