### ISSUE TITLE
German NumPad Decimal separator not accepted

### ISSUE THREAD

**Issue by gmoccapy** [FernV/NativeCAM#3]
I use latest NativeCam and German keyboard layout. In Germany we use "," as decimal separator, not ".". If I use the NumPad, the German decimal separator is ignored, but shouldn't.

I found a solution:
edit line 810 from ncam.py
`elif k_name in ['KP_Decimal', 'period', 'comma', 'KP_Separator'] :`

Norbert

**Comment by FernV** [comment]
Thanks Norbert, I did not know about 'KP_Separator'

Added for next release
